apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
